import type { Invoice, MouvementBancaire, Reconciliation, Fournisseur, Client } from '@/lib/rapprochement-types'

// Fournisseurs
export const fournisseurs: Fournisseur[] = [
  {
    id: 'f1',
    raisonSociale: 'ELECTROTECH MAROC',
    ice: '002345678901234',
    delaiPaiement: 30,
  },
  {
    id: 'f2',
    raisonSociale: 'FOURNITURES BUREAU PLUS',
    ice: '002987654321098',
    delaiPaiement: 15,
  },
  {
    id: 'f3',
    raisonSociale: 'TRANSPORT EXPRESS MAGHREB',
    ice: '002111222333444',
    delaiPaiement: 45,
  },
]

// Clients
export const clients: Client[] = [
  {
    id: 'c1',
    raisonSociale: 'SOCIÉTÉ MINIÈRE PHOSBOUCRAA',
    ice: '002555666777888',
    delaiPaiement: 60,
  },
  {
    id: 'c2',
    raisonSociale: 'COOPÉRATIVE AGRICOLE SOUSS',
    ice: '002333444555666',
    delaiPaiement: 30,
  },
]

// Plan comptable
export const comptesCharges = [
  { code: '6111', label: 'Achats de marchandises' },
  { code: '6121', label: 'Achats de matières et fournitures consommables' },
  { code: '6122', label: 'Achats non stockés de matières et de fournitures' },
  { code: '612270', label: 'Fournitures bureau' },
  { code: '6125', label: 'Achats de travaux, études et prestations de services' },
  { code: '612500', label: 'Matériel informatique' },
  { code: '6131', label: 'Locations et charges locatives' },
  { code: '6132', label: 'Redevances de crédit-bail' },
  { code: '6133', label: 'Entretien et réparations' },
  { code: '6134', label: 'Primes d\'assurances' },
  { code: '6135', label: 'Rémunérations du personnel extérieur à l\'entreprise' },
  { code: '6136', label: 'Rémunérations d\'intermédiaires et honoraires' },
  { code: '6141', label: 'Frais postaux et frais de télécommunications' },
  { code: '6142', label: 'Transports' },
  { code: '6143', label: 'Déplacements, missions et réceptions' },
  { code: '6144', label: 'Publicité, publications et relations publiques' },
  { code: '6145', label: 'Frais de personnel' },
  { code: '6161', label: 'Impôts, taxes et droits assimilés' },
  { code: '6171', label: 'Rémunérations du personnel' },
  { code: '6174', label: 'Charges sociales' },
  { code: '6182', label: 'Pertes sur créances irrécouvrables' },
  { code: '619', label: 'Dotations d\'exploitation' },
];

export const comptesProduits = [
  { code: '7111', label: 'Ventes de marchandises au Maroc' },
  { code: '7112', label: 'Ventes de marchandises à l\'étranger' },
  { code: '7121', label: 'Ventes de produits finis' },
  { code: '7122', label: 'Ventes de produits intermédiaires' },
  { code: '7124', label: 'Travaux, services vendus' },
  { code: '7127', label: 'Ventes de produits accessoires' },
  { code: '713', label: 'Variation des stocks de produits' },
  { code: '714', label: 'Immobilisations produites par l\'entreprise pour elle-même' },
  { code: '716', label: 'Subventions d\'exploitation' },
  { code: '718', label: 'Autres produits d\'exploitation' },
  { code: '719', label: 'Reprises d\'exploitation, transferts de charges' },
];

// Factures
export const invoices: Invoice[] = [
  {
    id: 'inv1',
    type: 'RECUE',
    numero: 'FA-2026-0142',
    tiersId: 'f1',
    tiersNom: 'ELECTROTECH MAROC',
    dateEmission: new Date('2026-01-15'),
    source: 'ERP',
    montantHT: 50000,
    montantTva: 10000,
    montantTTC: 60000,
    devise: 'MAD',
    status: 'RAPPROCHE',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'inv2',
    type: 'RECUE',
    numero: 'FA-2026-0187',
    tiersId: 'f2',
    tiersNom: 'FOURNITURES BUREAU PLUS',
    dateEmission: new Date('2026-02-01'),
    source: 'MANUELLE',
    montantHT: 15000,
    montantTva: 3000,
    montantTTC: 18000,
    devise: 'MAD',
    status: 'SUGGESTION_EN_ATTENTE',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'inv3',
    type: 'RECUE',
    numero: 'FA-2026-0234',
    tiersId: 'f3',
    tiersNom: 'TRANSPORT EXPRESS MAGHREB',
    dateEmission: new Date('2026-02-20'),
    source: 'OCR',
    montantHT: 85000,
    montantTva: 11900,
    montantTTC: 96900,
    devise: 'MAD',
    status: 'NON_RAPPROCHEE',
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'inv4',
    type: 'EMISE',
    numero: 'FC-2026-0089',
    tiersId: 'c1',
    tiersNom: 'SOCIÉTÉ MINIÈRE PHOSBOUCRAA',
    dateEmission: new Date('2026-01-25'),
    source: 'ERP',
    montantHT: 350000,
    montantTva: 70000,
    montantTTC: 420000,
    devise: 'MAD',
    status: 'RAPPROCHE',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'inv5',
    type: 'EMISE',
    numero: 'FC-2026-0112',
    tiersId: 'c2',
    tiersNom: 'COOPÉRATIVE AGRICOLE SOUSS',
    dateEmission: new Date('2026-02-10'),
    source: 'MANUELLE',
    montantHT: 120000,
    montantTva: 24000,
    montantTTC: 144000,
    devise: 'MAD',
    status: 'JUSTIFIE',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'inv6',
    type: 'RECUE',
    numero: 'FA-2026-0445',
    tiersId: 'f1',
    tiersNom: 'ELECTROTECH MAROC',
    dateEmission: new Date('2026-02-20'),
    source: 'MANUELLE',
    montantHT: 100000,
    montantTva: 20000,
    montantTTC: 120000,
    devise: 'MAD',
    status: 'RAPPROCHE',
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'inv7',
    type: 'RECUE',
    numero: 'FA-2026-0598',
    tiersId: 'f3',
    tiersNom: 'TRANSPORT EXPRESS MAGHREB',
    dateEmission: new Date('2026-02-28'),
    source: 'OCR',
    montantHT: 75000,
    montantTva: 10500,
    montantTTC: 85500,
    devise: 'MAD',
    status: 'ECART_DETECTE',
    createdAt: new Date('2026-02-28'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: 'inv8',
    type: 'RECUE',
    numero: 'FA-2026-0723',
    tiersId: 'f2',
    tiersNom: 'FOURNITURES BUREAU PLUS',
    dateEmission: new Date('2026-03-01'),
    source: 'ERP',
    montantHT: 42000,
    montantTva: 8400,
    montantTTC: 50400,
    devise: 'MAD',
    status: 'NON_RAPPROCHEE',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
]

// Mouvements Bancaires
export const mouvementsBancaires: MouvementBancaire[] = [
  {
    id: 'mv1',
    reference: 'CBS-REF-001201',
    dateValeur: new Date('2026-01-16'),
    montant: -60000,
    libelle: 'TRANSFERT ELECTROTECH MAROC',
    banque: 'CAM',
    sens: 'DEBIT',
  },
  {
    id: 'mv2',
    reference: 'CBS-REF-001450',
    dateValeur: new Date('2026-02-03'),
    montant: -18200,
    libelle: 'VIR FOURNITURES BUREAU',
    banque: 'CAM',
    sens: 'DEBIT',
  },
  {
    id: 'mv3',
    reference: 'CBS-REF-001678',
    dateValeur: new Date('2026-02-21'),
    montant: -96000,
    libelle: 'TRANSPORT MAGHREB',
    banque: 'CAM',
    sens: 'DEBIT',
  },
  {
    id: 'mv4',
    reference: 'CBS-REF-001999',
    dateValeur: new Date('2026-01-27'),
    montant: 420000,
    libelle: 'VIR RECU PHOSBOUCRAA',
    banque: 'CAM',
    sens: 'CREDIT',
  },
  {
    id: 'mv5',
    reference: 'CBS-REF-002045',
    dateValeur: new Date('2026-02-12'),
    montant: 140000,
    libelle: 'VIR RECU COOPÉRATIVE SOUSS',
    banque: 'CAM',
    sens: 'CREDIT',
  },
  {
    id: 'mv6',
    reference: 'CBS-REF-002234',
    dateValeur: new Date('2026-02-21'),
    montant: -120000,
    libelle: 'ELECTROTECH FACTURE 0445',
    banque: 'CAM',
    sens: 'DEBIT',
  },
  {
    id: 'mv7',
    reference: 'CBS-REF-002567',
    dateValeur: new Date('2026-03-02'),
    montant: -50000,
    libelle: 'FOURNITURES BUREAU',
    banque: 'CAM',
    sens: 'DEBIT',
  },
]

// Reconciliations - combiner factures + mouvements
export const reconciliations: Reconciliation[] = [
  {
    id: 'r1',
    invoice: invoices[0],
    mouvement: mouvementsBancaires[0],
    score: { montant: 40, date: 25, referenceFacture: 20, contrepartie: 8, total: 93 },
    status: 'RAPPROCHEE',
    validationDate: new Date('2026-01-16'),
  },
  {
    id: 'r2',
    invoice: invoices[1],
    mouvement: mouvementsBancaires[1],
    score: { montant: 38, date: 23, referenceFacture: 15, contrepartie: 6, total: 82 },
    status: 'SUGGESTION_EN_ATTENTE',
  },
  {
    id: 'r3',
    invoice: invoices[2],
    mouvement: mouvementsBancaires[2],
    score: { montant: 35, date: 18, referenceFacture: 12, contrepartie: 5, total: 70 },
    status: 'ECART_DETECTE',
    justification: 'Écart de 3900 MAD, vérification en cours',
  },
  {
    id: 'r7b',
    invoice: invoices[7],
    mouvement: undefined,
    score: { montant: 0, date: 0, referenceFacture: 0, contrepartie: 0, total: 0 },
    status: 'NON_RAPPROCHEE',
  },
  {
    id: 'r4',
    invoice: invoices[3],
    mouvement: mouvementsBancaires[3],
    score: { montant: 40, date: 25, referenceFacture: 22, contrepartie: 9, total: 96 },
    status: 'RAPPROCHEE',
    validationDate: new Date('2026-01-27'),
  },
  {
    id: 'r5',
    invoice: invoices[4],
    mouvement: mouvementsBancaires[4],
    score: { montant: 40, date: 25, referenceFacture: 18, contrepartie: 8, total: 91 },
    status: 'RAPPROCHEE',
    validationDate: new Date('2026-02-12'),
  },
  {
    id: 'r6',
    invoice: invoices[5],
    mouvement: mouvementsBancaires[5],
    score: { montant: 40, date: 24, referenceFacture: 19, contrepartie: 7, total: 90 },
    status: 'RAPPROCHEE',
    validationDate: new Date('2026-02-21'),
  },
  {
    id: 'r7',
    invoice: invoices[6],
    mouvement: undefined,
    score: { montant: 0, date: 0, referenceFacture: 0, contrepartie: 0, total: 0 },
    status: 'NON_RAPPROCHEE',
  },
  {
    id: 'r8',
    invoice: invoices[7],
    mouvement: mouvementsBancaires[6],
    score: { montant: 39, date: 22, referenceFacture: 14, contrepartie: 5, total: 80 },
    status: 'SUGGESTION_EN_ATTENTE',
  },
]

export const additionalReconciliations: Reconciliation[] = []
